# Generated by Django 4.2.28 on 2026-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner_id',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('owner_id', 'name'), name='uniq_item_name_per_user'),
        ),
    ]
